---
  - name: install and start the servers
    yum:
      name:
        - mariadb
        - httpd
      state: latest

  - name: start db server
    service:
      name: mariadb
      state: started
      enabled: true

  - name: start the web service
    service: 
      name: httpd
      state: started
      enabled: true
 
