---
- name: error handling
  hosts: all
  tasks:
    - block:
      - name: upgrade the database
        shell:
          cmd: /usr/local/lib/upgrade-database
      rescue:
      - name: revert after failure
        shell:
          cmd: /usr/local/lib/revert-database
      always:
      - name: always restart the database
        service: 
          name: mariadb
          state: restarted
