---
# tasks file for mountweb
- name: setup webserver
  hosts: webservers
  tasks:
  - name: create partition
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: 2G
  - name: create filesystem
    filesystem:
      fstype: xfs
      dev: /dev/sdb1
      force: no
  - name: mount
    mount:
      path: /web
      src: /dev/sdb1
      fstype: xfs
      state: present
  - name: set_selinux
    sefcontext:
      setype: httpd_sys_content_t
      target: '/web(/.*)?'
      state: present
  - name: run_restorecon
    command: 'restorecon -r /web'

