---
[packages]
web_package: httpd
ftp_package: vsftpd
db_package: mariadb-server
firewall_package: firewalld

[services]
web_service: httpd
ftp_service: vsftpd
db_service: mariadb
firewall_service: firewalld
