---
- name: configure LVM
  hosts: ansible2.example.com
  tasks: 
  - name: create partition
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: 2G
  - name: create filesystem
    filesystem:
      fstype: xfs
      dev: /dev/sdb1
      force: no
  - name: mount
    mount:
      path: /web
      src: /dev/sdb1
      fstype: xfs
      state: present
